console.log('Предположение: number');
console.log('Фактически:', typeof 9);
console.log('Предположение: number');
console.log('Фактически:', typeof(1.2));
console.log('Предположение: number');
console.log('Фактически:', typeof(NaN));
console.log('Предположение: string');
console.log('Фактически:', typeof("Hello World"));
console.log('Предположение: bool');
console.log('Фактически:', typeof(true));
console.log('Предположение: bool');
console.log('Фактически:', typeof(2 != 1));
console.log('Предположение: string');
console.log('Фактически:', typeof("сыр" + "ы"));
console.log('Предположение: string');
console.log('Фактически:', typeof("сыр" - "ы"));
console.log('Предположение: string');
console.log('Фактически:', typeof("2" + "4"));
console.log('Предположение: string');
console.log('Фактически:', typeof("2" - "4"));
console.log('Предположение: string');
console.log('Фактически:', typeof("Сэм" + 5));
console.log('Предположение: string');
console.log('Фактически:', typeof("Сэм" - 5));
console.log('Предположение: string');
console.log('Фактически:', typeof(99 * "шары"));